# Dockerfile-globalServer
FROM python:3.12.6

# Set up working directory
WORKDIR /app

# Copy global server files
COPY . /app


# Install required packages
RUN pip install -r requirements.txt

# Set the entrypoint
ENTRYPOINT ["python", "intermediate_server1.py"]
