# Dockerfile-SmartMeters
FROM python:3.12.6

# Set up working directory
WORKDIR /app

# Copy client files
COPY . /app

# Install required packages
RUN pip install -r requirements.txt

# Set the entrypoint
ENTRYPOINT ["python", "Client.py","1","5003"]
